### PR TITLE
Read config from configured name path instead of static 'redis' key

### PR DESCRIPTION
**Pull request by dschmidt**
https://github.com/ember-cli/ember-cli-deploy/pull/195 has landed and I added tests.

So this is good to go from my POV.

### CODE REVIEW

**Comment by lukemelia** [comment]
A good test might be to read the redisDeployClient from config after running the configure hook and validating the values.

**Comment by lukemelia** [comment]
:+1:

**Comment by achambers** [comment]
Is this good to go @dschmidt ?

**Comment by dschmidt** [comment]
Indeed, it is from my POV. If you're fine with it, merge it :)

**Comment by achambers** [comment]
Thanks dude!

**Pull request merged**
